general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: []
    parallels:
       priority_level_1: []
    ss_drivetrain:
      priority_level_1: []
      default: [st_drivetrain]


  subsystems: [ss_drivetrain]

  input_booleans: []

  input_numerics: [ipn_driver_left_y, ipn_driver_right_y]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right]

  output_booleans: []


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  y-left: ipn_driver_left_y
  y-right: ipn_driver_right_y

log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

